/**
 * Las 12 listas desplegables definidas en la hoja "Listas" de formats/formato_SOP.xlsx.
 * Del Excel original, 6 de las 12 (FRECUENCIA_CORTA, MODO_TRANSPORTE, ESTADO_DOCUMENTO,
 * PRIORIDAD, SERVICIOS, TIPO_COMUNICACION) quedaron preparadas en la hoja "Listas" pero sin
 * conectar a ninguna celda vía validación de datos. Se conectan aquí a su campo más afín
 * (ver PLAN-IMPLEMENTACION.md, sección Fase 2) para que ninguna lista del formato se pierda.
 */

export const OPCIONES_SI_NO_NA = ["Sí", "No", "N/A"] as const;

export const OPCIONES_FRECUENCIA_CORTA = [
  "Diario",
  "Semanal",
  "Quincenal",
  "Mensual",
  "Por evento",
  "Tiempo real",
] as const;

export const OPCIONES_CANAL_ODOO = [
  "Correo - Odoo",
  "WhatsApp - Odoo",
  "Llamada - Odoo",
  "Teams - Odoo",
] as const;

export const OPCIONES_NIVEL_CLIENTE = ["Nivel 1", "Nivel 2", "Nivel 3"] as const;

export const OPCIONES_FRECUENCIA_LARGA = ["Mensual", "Trimestral", "Semestral", "Anual"] as const;

export const OPCIONES_TIPO_OPERACION = ["Importación", "Exportación", "Ambos"] as const;

export const OPCIONES_MODO_TRANSPORTE = ["Marítimo", "Aéreo", "Terrestre", "Multimodal"] as const;

export const OPCIONES_ESTADO_DOCUMENTO = ["Abierto", "En revisión", "Obsoleto", "Aprobado"] as const;

export const OPCIONES_PRIORIDAD = ["Alta", "Media", "Baja"] as const;

export const OPCIONES_AREA_RESPONSABLE = [
  "Comercial",
  "Operaciones",
  "Customer Service / KAS",
  "Facturación",
  "Almacenamiento / Bodega",
  "Calidad",
  "Gerencia",
] as const;

export const OPCIONES_SERVICIOS = [
  "OTM / DTA",
  "Transporte nacional",
  "Transporte internacional",
  "Aduanas",
  "Almacenamiento / Bodega",
] as const;

export const OPCIONES_FRECUENCIA_COMUNICACION = ["1 por semana", "2 por semana", "Quincenal"] as const;

export const OPCIONES_TIPO_COMUNICACION = ["Informativa", "Preventiva", "Alertas"] as const;

// Lista cerrada de países (ISO, en español, orden alfabético) para evitar
// variantes de escritura ("Colombia" / "colombia" / "COL") en el campo País.
export const OPCIONES_PAIS = [
  "Afganistán",
  "Albania",
  "Alemania",
  "Andorra",
  "Angola",
  "Antigua y Barbuda",
  "Arabia Saudita",
  "Argelia",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaiyán",
  "Bahamas",
  "Bangladés",
  "Barbados",
  "Baréin",
  "Bélgica",
  "Belice",
  "Benín",
  "Bielorrusia",
  "Birmania (Myanmar)",
  "Bolivia",
  "Bosnia y Herzegovina",
  "Botsuana",
  "Brasil",
  "Brunéi",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Bután",
  "Cabo Verde",
  "Camboya",
  "Camerún",
  "Canadá",
  "Catar",
  "Chad",
  "Chile",
  "China",
  "Chipre",
  "Ciudad del Vaticano",
  "Colombia",
  "Comoras",
  "Corea del Norte",
  "Corea del Sur",
  "Costa de Marfil",
  "Costa Rica",
  "Croacia",
  "Cuba",
  "Dinamarca",
  "Dominica",
  "Ecuador",
  "Egipto",
  "El Salvador",
  "Emiratos Árabes Unidos",
  "Eritrea",
  "Eslovaquia",
  "Eslovenia",
  "España",
  "Estados Unidos",
  "Estonia",
  "Esuatini",
  "Etiopía",
  "Filipinas",
  "Finlandia",
  "Fiyi",
  "Francia",
  "Gabón",
  "Gambia",
  "Georgia",
  "Ghana",
  "Granada",
  "Grecia",
  "Guatemala",
  "Guinea",
  "Guinea ecuatorial",
  "Guinea-Bisáu",
  "Guyana",
  "Haití",
  "Honduras",
  "Hungría",
  "India",
  "Indonesia",
  "Irak",
  "Irán",
  "Irlanda",
  "Islandia",
  "Islas Marshall",
  "Islas Salomón",
  "Israel",
  "Italia",
  "Jamaica",
  "Japón",
  "Jordania",
  "Kazajistán",
  "Kenia",
  "Kirguistán",
  "Kiribati",
  "Kuwait",
  "Laos",
  "Lesoto",
  "Letonia",
  "Líbano",
  "Liberia",
  "Libia",
  "Liechtenstein",
  "Lituania",
  "Luxemburgo",
  "Macedonia del Norte",
  "Madagascar",
  "Malasia",
  "Malaui",
  "Maldivas",
  "Malí",
  "Malta",
  "Marruecos",
  "Mauricio",
  "Mauritania",
  "México",
  "Micronesia",
  "Moldavia",
  "Mónaco",
  "Mongolia",
  "Montenegro",
  "Mozambique",
  "Namibia",
  "Nauru",
  "Nepal",
  "Nicaragua",
  "Níger",
  "Nigeria",
  "Noruega",
  "Nueva Zelanda",
  "Omán",
  "Países Bajos",
  "Pakistán",
  "Palaos",
  "Panamá",
  "Papúa Nueva Guinea",
  "Paraguay",
  "Perú",
  "Polonia",
  "Portugal",
  "Reino Unido",
  "República Centroafricana",
  "República Checa",
  "República del Congo",
  "República Democrática del Congo",
  "República Dominicana",
  "Ruanda",
  "Rumanía",
  "Rusia",
  "Samoa",
  "San Cristóbal y Nieves",
  "San Marino",
  "San Vicente y las Granadinas",
  "Santa Lucía",
  "Santo Tomé y Príncipe",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leona",
  "Singapur",
  "Siria",
  "Somalia",
  "Sri Lanka",
  "Sudáfrica",
  "Sudán",
  "Sudán del Sur",
  "Suecia",
  "Suiza",
  "Surinam",
  "Tailandia",
  "Tanzania",
  "Tayikistán",
  "Timor Oriental",
  "Togo",
  "Tonga",
  "Trinidad y Tobago",
  "Túnez",
  "Turkmenistán",
  "Turquía",
  "Tuvalu",
  "Ucrania",
  "Uganda",
  "Uruguay",
  "Uzbekistán",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Yibuti",
  "Zambia",
  "Zimbabue",
] as const;

// Ciudades sugeridas para el autocompletado del campo Ciudad. Cubre las
// capitales de departamento de Colombia (mercado principal de Turinza); para
// otros países el campo admite escritura libre.
export const CIUDADES_SUGERIDAS_COLOMBIA = [
  "Bogotá D.C.",
  "Medellín",
  "Cali",
  "Barranquilla",
  "Cartagena",
  "Cúcuta",
  "Bucaramanga",
  "Pereira",
  "Santa Marta",
  "Ibagué",
  "Pasto",
  "Manizales",
  "Neiva",
  "Villavicencio",
  "Armenia",
  "Valledupar",
  "Montería",
  "Sincelejo",
  "Popayán",
  "Tunja",
  "Florencia",
  "Riohacha",
  "Yopal",
  "Quibdó",
  "Arauca",
  "Mocoa",
  "San José del Guaviare",
  "Mitú",
  "Puerto Carreño",
  "Leticia",
  "Inírida",
  "San Andrés",
] as const;
