export const SECTORES_INDUSTRIA: string[] = [
  "Agricultura",
  "Ganadería",
  "Pesca y acuicultura",
  "Silvicultura y explotación forestal",
  "Minería",
  "Petróleo y gas",
  "Energía eléctrica",
  "Energías renovables",
  "Agua y saneamiento",
  "Gestión de residuos y reciclaje",
  "Construcción",
  "Ingeniería y obras civiles",
  "Arquitectura y diseño",
  "Manufactura",
  "Industria automotriz",
  "Industria aeronáutica",
  "Industria naval",
  "Industria ferroviaria",
  "Industria metalúrgica",
  "Siderurgia",
  "Fabricación de maquinaria y equipos",
  "Electrónica",
  "Semiconductores",
  "Tecnología",
  "Software",
  "Servicios de tecnología de la información (TI)",
  "Ciberseguridad",
  "Inteligencia artificial",
  "Telecomunicaciones",
  "Internet y servicios digitales",
  "Computación en la nube",
  "Centros de datos",
  "Servicios de datos y analítica",
  "Comercio minorista (Retail)",
  "Comercio mayorista",
  "Comercio electrónico (E-commerce)",
  "Distribución",
  "Logística",
  "Transporte terrestre",
  "Transporte aéreo",
  "Transporte marítimo",
  "Transporte ferroviario",
  "Mensajería y paquetería",
  "Almacenamiento y bodegaje",
  "Automóviles y autopartes",
  "Alimentos y bebidas",
  "Restaurantes y gastronomía",
  "Hotelería",
  "Turismo y viajes",
  "Entretenimiento",
  "Cultura y arte",
  "Deportes y recreación",
  "Medios de comunicación",
  "Publicidad y marketing",
  "Telecomunicaciones y medios digitales",
  "Educación",
  "Capacitación y formación",
  "Salud",
  "Servicios médicos",
  "Servicios odontológicos",
  "Farmacéutica",
  "Biotecnología",
  "Investigación científica",
  "Salud y bienestar",
  "Belleza y estética",
  "Seguros",
  "Banca",
  "Servicios financieros",
  "Fintech",
  "Inversiones",
  "Mercado de valores",
  "Contabilidad y auditoría",
  "Consultoría empresarial",
  "Servicios jurídicos",
  "Recursos humanos",
  "Servicios profesionales",
  "Inmobiliario",
  "Administración de propiedades",
  "Servicios de limpieza y mantenimiento",
  "Seguridad privada",
  "Servicios administrativos",
  "Gobierno y administración pública",
  "Defensa y seguridad nacional",
  "Organizaciones sin ánimo de lucro",
  "Organizaciones internacionales",
  "Servicios sociales",
  "Moda y confección",
  "Textiles",
  "Calzado y marroquinería",
  "Cosméticos y cuidado personal",
  "Productos químicos",
  "Industria farmacéutica",
  "Plásticos y caucho",
  "Papel y cartón",
  "Madera y muebles",
  "Vidrio y cerámica",
  "Cemento y materiales de construcción",
  "Industria alimentaria",
  "Bebidas y productos alcohólicos",
  "Tabaco",
  "Joyería y artículos de lujo",
  "Comercio exterior",
  "Importación y exportación",
  "Servicios de outsourcing / BPO",
  "Call center / Contact center",
  "Consultoría tecnológica",
  "Desarrollo de aplicaciones",
  "Marketing digital",
  "Investigación de mercados",
  "Servicios creativos y diseño",
  "Energía nuclear",
  "Aeroespacial",
  "Defensa",
  "Impresión y artes gráficas",
  "Equipos médicos",
  "Instrumentación y tecnología médica",
  "Energía y servicios públicos",
  "Petróleo, gas y petroquímica",
  "Química industrial",
  "Economía circular",
  "Tecnología financiera",
  "Tecnología educativa (EdTech)",
  "Tecnología sanitaria (HealthTech)",
  "Tecnología inmobiliaria (PropTech)",
  "Tecnología agrícola (AgTech)",
  "Tecnología logística (LogTech)",
  "Videojuegos",
  "Realidad virtual y aumentada",
  "Inteligencia artificial y machine learning",
  "Blockchain y activos digitales",
  "Servicios de impresión 3D",
  "Robótica y automatización",
  "Investigación y desarrollo (I+D)",
  "Servicios ambientales",
  "Desarrollo sostenible",
  "Energía solar",
  "Energía eólica",
  "Economía digital",
  "Comercio internacional",
  "Otros servicios",
];
